#!/usr/bin/python3.11

import argparse
import src.installer as installer
import src.remover as remover
import src.stower as stower

arg_parser = argparse.ArgumentParser(description="The Arachnid Package Manager")

arg_parser.add_argument("-i", "--install", nargs=1, metavar="<package>", required=False)
arg_parser.add_argument("-r", "--remove", nargs=1, metavar="<package>", required=False)

args = arg_parser.parse_args()

if args.install:
    installer.build_and_install_package(args.install[0])

if args.remove:
    remover.remove_package(args.remove[0])
