#!/usr/bin/python3.11

import argparse
import src.builder as builder

arg_parser = argparse.ArgumentParser(description="The Arachnid Package Manager")

arg_parser.add_argument("-b", "--build", nargs=1, metavar="<file.toml>", required=False)

args = arg_parser.parse_args()

if args.build:
    builder.build_package(args.build[0])
