[meta]
name = "hello"
version = "2.12.1"
description = "The GNU Bourne Again shell"

[sources]
urls = [
    "https://ftp.gnu.org/gnu/hello/hello-2.12.1.tar.gz"
]

[build]
install = [
    "export CFLAGS=\"-O3 -pipe -march=native\"",
    "cd hello-2.12.1",
    "mkdir -p /opt/hello-2.12.1",
    "./configure --prefix=/usr",
    "make -j10",
    "make install DESTDIR=/opt/hello-2.12.1"
]
