[meta]
name = "bash"
version = 5.1
description = "The GNU Bourne Again shell"

[sources]
urls = [
    "https://ftp.gnu.org/gnu/bash/bash-5.1.tar.gz"
]

[build]
install = [
    "cd bash-5.1",
    "mkdir -p /opt/bash-5.1",
    "./configure --prefix=/usr",
    "make -j10",
    "make install DESTDIR=/opt/bash-5.1"
]
